# KB Card 파일 불러오기

## 0. 초기 세팅
각종 라이브러리를 불러오고 초기값 등을 세팅합니다.

In [1]:
#!uv add xlrd

In [6]:
import pandas as pd
from ledgerly.expenditure import (
    preprocess_kbcard_data,
    map_kb_card_df_to_expenditure,
    map_category,
    insert_expenditure_data,
)
from ledgerly.expenditure import kbcard_file_config

## 1. 데이터 파일 조회 및 전처리

In [ ]:
# 데이터 불러오기
raw_df = pd.read_excel(kbcard_file_config["kb_card_xls"], header=6)

# 데이터 전처리
df = preprocess_kbcard_data(raw_df)

,이용일,이용시간,이용고객명,이용카드명,이용하신곳,국내이용금액(원),해외이용금액($),결제방법,가맹점정보,할인금액,적립(예상)포인트리,상태,결제예정일,승인번호
15,2026-01-26,05:48:00,임준열,KB국민 가온올림카드(실속형),김포감정주유소,-140000,0,일시불,<NA>,0,0,승인취소,NaT,30119124
43,2026-01-15,05:52:00,임준열,KB국민 가온올림카드(실속형),김포감정주유소,-140000,0,일시불,<NA>,0,0,승인취소,NaT,30118695

## 2. DB 데이터로 매핑

In [21]:
expenditure_df = map_kb_card_df_to_expenditure(df)
expenditure_df[expenditure_df["amount"] < 0]

Empty DataFrame
Columns: [used_at, payment_type, payment_provider, merchant_name, installment_type, amount, remaining_amount, category, memo, source_uid]
Index: []

## 3. 지출 분류

In [ ]:
expenditure_df["category"] = expenditure_df["merchant_name"].apply(map_category)
expenditure_df["category"] = expenditure_df["category"].fillna("미분류")

## 4. DB 저장

In [12]:
insert_expenditure_data(expenditure_df)
print(f"{len(expenditure_df)}개의 데이터가 성공적으로 저장되었습니다.")

73개의 데이터가 성공적으로 저장되었습니다.